.\"
.\" cmp_ppm.1 - the *roff document processor man page source
.\"
.TH cmp_ppm 1 "98/07/08" "Watermarking, Version 1.0"
.SH NAME
cmp_ppm \- a program to create the difference image of two PGM images
.SH SYNOPSIS
.B cmp_ppm
[
.BI \-c \ name
]
[
.B \-h
]
[
.BI \-m \ number
]
[
.BI \-o \ ofile
]
.BI \-i \ ifile
.I file
.SH DESCRIPTION
.B cmp_ppm
is a program to create the difference image of two PPM (portable pixmap)
RGB color images. To compare PGM (portable graymap) grayscale images, use
the
.B cmp_pgm
program.
.PP
The color components to compare are specified with the
.BI \-c \ name
option, where
.I name
is one of the following:
.TP
.B red
The red color component.
.TP
.B green
The green color component.
.TP
.B blue
The blue color component.
.PP
Multiple color components are allowed. Specifying only the inital letter
of a color component is sufficient.
Per default
.B cmp_ppm
compares the luminance value of the images. This operation may be
selected explicitly with the
.BI \-c \ luminance
option.
.PP
If
.I file
or
.I ofile
is not specified, then standard input or standard output is
used.
.PP
.SH OPTIONS
.TP
.BI \-c \ name
Specifies color component(s) or luminance to compare. Default: luminance.
.TP
.B \-h
Print a help message.
.TP
.BI \-i \ ifile
The original image. Mandatory.
.TP
.BI \-m \ number
Multiplication factor to magnify differences between the to
original and input image.
Default value: 16.
.TP
.BI \-o \ ofile
Output image file to contain the difference image in PPM format.
.TP
.I file
Input image that is compared against
.I ifile.
Default: standard input.
.SH OUTPUT
The difference image in PPM format is written to standard output or,
optionally, to
.I ofile.
.SH AUTHOR
Peter Meerwald.
Email bug reports to pmeerw@cosy.sbg.ac.at.
.SH AVAILABILITY
The most recent released version of
.B cmp_ppm
is always available
at http://www.cosy.sbg.ac.at/~pmeerw/Watermarking or via anonymous ftp from ftp.cosy.sbg.ac.at in the
directory /pub/people/pmeerw/Watermarking.
.SH "SEE ALSO"
.B cmp_ppm
(1)
