.\"
.\" gen_bruyn_sig.1 - the *roff document processor man page source
.\"
.TH gen_bruyn_sig 1 "98/06/30" "Watermarking, Version 1.0"
.SH NAME
gen_bruyn_sig \- an man page source template
.SH SYNOPSIS
.B gen_bruyn_sig
[
.B \-abcdef
]
[
.BI \-d opt
]
[
.BI \-o file
]
[
.IR files \|.\|.\|.\|
]
.SH DESCRIPTION
.B gen_bruyn_sig
is a program.
.PP
the
.B \-d
option is one of the following:
.TP
.B opt1 for option 1
.TP
.B opt2 for option 2
.TP
.B opt3 for option 3
.LP
I hope you can guess the purpose of the program.
.LP
Can you?
.P
.SH OPTIONS
.TP
.B \-a
option a
.TP
.B \-b
option b
.TP
.B \-c
option c
.TP
.B \-d
option d
.TP
.B \-e
option e
.TP
.B \-f
option f
.PP
These are all the options, now on with some environment variables:
.TP
.SM
.B ENV_VAR1
environment variable 1
.TP
.SM
.B ENV_VAR2
environment variable 2
.TP
.SM
.B ENV_VAR3
environment variable 2
.SH FILES
.SH AUTHOR
Peter Meerwald <pmeerw@cosy.sbg.ac.at>
.SH NOTES
.SH BUGS
Email bug reports to pmeerw@cosy.sbg.ac.at.
.SH COPYRIGHT
Copyright \(co 1998 Peter Meerwald
.SH AVAILABILITY
The most recent released version of
.B gen_bruyn_sig
is always available
at http://www.cosy.sbg.ac.at/~pmeerw/Watermarking or via anonymous ftp from ftp.cosy.sbg.ac.at in the
directory /pub/people/pmeerw/Watermarking.
.SH "SEE ALSO"
.BR program1,
.BR program2,
.BR program3
